### PR TITLE
Update Mbed-CHIP build integration to add support for project specific CHIP configuration.

### PR DESCRIPTION
**Pull request by lukgni**
#### Problem

- Missing possibility to configure CHIP Device/System layer from project level.
- System, Platform and Device layers configuration are merged together inside one file (`CHIPDevicePlatformConfig.h`).
- This forced us to use the same Device Layer configuration across all Mbed targets.

  

 #### Summary of Changes

- Add file with default project configuration: `config/mbed/CHIPProjectConfig.h`
- Modify `config/mbed/CMakeList.txt` to use default project config file ( `config/mbed/CHIPProjectConfig.h`) if project doesn't have it's own. 
- Move device specific configuration flags from `CHIPPlatformConfig.h `to `config/mbed/CHIPProjectConfig.h`  which can be easily override by project application. 
- Update mbed/shell example to work with proposed change.

Required by #34

### CODE REVIEW

**Comment by ATmobica** [comment]
@lukgni I think according to the chip architecture the project-specific configuration file (CHIPProjectDefualtConfig.h) should be put to examples/platform/mbed directory, In src/platform/mbed are platform-specific files.

**Review by ATmobica — APPROVED** [review]

**Comment by lukgni** [comment]
@ATmobica You're right that src/platform/mbed is not the best place for CHIPProjectDefualtConfig.h. 
I thought the same when I created this PR by I couldn't figure out better place for that file yesterday.
However, now I think that we should place  CHIPProjectDefualtConfig.h in config/mbed path and follow approach taken by config/ios and config/android. We still need some default configuration for couple of features, for building CHIP as standalone library. That's why /config/mbed looks more intuitive for me than examples/platform/mbed

**Comment by ATmobica** [comment]
@lukgni  Right, agree that config/mbed will be a good place.

**Review by ATmobica — APPROVED** [review]

**Comment by pan-** [comment]
Is that header automatically included for every file compiled ? How does it impact existing application like shell ?

**Comment by lukgni** [comment]
@pan- Nope, It's only included only in `src/lib/core/CHIPConfig.h` and `src/system/SystemConfig.h` which configure other CHIP components like ConnectivityManager, CHIPCore etc.
This means that flags placed in `CHIPProjectConfig.h` have similiar scope/effect as it would be placed in `CHIPPlatformConfig.h`

**Pull request merged**
