### PR TITLE
Remove unused container environment variable in examples-mbed.yaml

### PR DESCRIPTION
**Pull request by lukgni**
I forgot to remove some test variable which I tried to use as workaround for passing secrets.DOCKERHUB_USERNAME to container.image context.

 #### Problem
Unused **container.env.image_name** variable in examples-mbed.yaml.

 #### Summary of Changes
Removed unused variable in examples-mbed.yaml.

### CODE REVIEW

**Review by fkjagodzinski — APPROVED** [review]
This patch looks fine. We have to fix the credentials though.. The username and password seem to be invalid.

**Comment by lukgni** [comment]
It looks like secrets are correct:
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository. The permissions for the GITHUB_TOKEN in forked repositories is read-only. For more information, see "Authenticating with the GITHUB_TOKEN."

[SOURCE]](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)

**Comment by pan-** [comment]
@lukgni We would just need the credentials if the image was private and that is not the case. Can you remove the credentials map in that build file ?

**Comment by lukgni** [comment]
@pan- Yep, that's true - I removed credentials from my PR.

**Review by fkjagodzinski — APPROVED** [review]
Nice! Good to see the _Build example - Mbed OS_ green again. :+1:

**Pull request merged**
