### PR TITLE
Add 'cortex-debug' to .devcontainer.json

### LINKED ISSUE #181: Add 'cortex-debug' extension to devcontainer.json
#### Problem
The 'cortex-debug' extension is not installed by default when opening vscode inside the container.
That extension is used during debugging process for mbed-os targets

 #### Proposed Solution
Add 'cortex-debug' extension to devcontainer.json

### PR DESCRIPTION
**Pull request by lukgni**
#### Problem
The 'cortex-debug' extension is not installed by default when opening vscode inside the container.
That extension is used during debugging process for mbed-os targets

 #### Summary of Changes
Add 'cortex-debug' to .devcontainer.json

 Fixes #181

### CODE REVIEW

**Comment by pan-** [comment]
The extension installation is suggested at the moment. Is that not enough ?

**Review by ATmobica — APPROVED** [review]

**Comment by lukgni** [comment]
@pan- It depends on approach how we should deal with the vscode inside the container.
My assumption was that running vscode in that way should give user complete development environment, without need to install anything manually (we can think about it as a 'ready-to-go" solution).

**Review by pan- — APPROVED** [review]
I'm happy with it. 
Can you submit the same patch upstream ?

**Comment by lukgni** [comment]
@pan- Sure, here you go:  #8122

**Pull request merged**
