### PR TITLE
vscode: Use pan2048/chip-build-mbed-os image

### PR DESCRIPTION
**Pull request by fkjagodzinski**
#### Problem

We need a common developer env that is easy to reproduce.

Even though we already have a `chip-build-vscode` Docker image (that is built on top of a few target specific ones, including the Mbed OS) we still have to figure out a way to provide the `mbedtools` in the `PATH` of that image.

 #### Summary of Changes

This is a TEMPORARY workaround to have the `mbedtools` command available when reopening the vscode workspace in a container.

### CODE REVIEW

**Review by lukgni — APPROVED** [review]

**Comment by ATmobica** [comment]
Just for clarity: is it not necessary to change VERSION to "0.5.0" for this solution?

**Comment by lukgni** [comment]
Currently .devcontainer uses BUILD_VERSION=latest.
We pushed chip-build-mbed-os:latest to docker.hub yesterday: [[LINK]](https://hub.docker.com/r/pan2048/chip-build-mbed-os/tags?page=1&ordering=last_updated) so proposed change should works fine.

**Comment by fkjagodzinski** [comment]
@ATmobica Yeah, `latest` is fine. We just have to push every new image under this tag (which I assume we'll do). And we won't have to update the version param ever again. :slightly_smiling_face:

**Comment by ATmobica** [comment]
Great, thanks!

**Review by ATmobica — APPROVED** [review]

**Review by pan- — APPROVED** [review]

**Pull request merged**
