### PR TITLE
Fix mbed-os symlink in mbed_example.sh

### PR DESCRIPTION
**Pull request by fkjagodzinski**
#### Problem

Consecutive runs of the `Build nRF mbed shell Example` vscode task log an error:
```
ln: failed to create symbolic link shell/mbed/mbed-os/mbed-os: Permission denied
```

 #### Summary of Changes

Add a `-T` flag and always treat the destination as a normal file, not directory.

### CODE REVIEW

**Comment by pan-** [comment]
Thanks @fkjagodzinski I think we should drop the demo branch and port these changes to development.

**Comment by fkjagodzinski** [comment]
Sure, I can redirect this patch to the `development`, but the `scripts/examples/mbed_example.sh` file does not exist there yet.

**Comment by pan-** [comment]
Yes this is something I should have done today 😓 . That will probably wait tomorrow.

**Comment by fkjagodzinski** [comment]
Dropped in favor of #39.

**Pull request closed without merging**
